#!/usr/bin/env bash

getprice () {
  # replace with your preferred exchange
  curl -sL 'https://api.bitfinex.com/v2/tickers?symbols=tBTCUSD' | jq '.[0][1]'
  #curl -sL 'https://api.quadrigacx.com/v2/ticker' | jq -r .last
}


n=${1:-100}
estimate_mode=${2:-UNSET}
size=${3:-226}
price=${4:-$(getprice)}

case $estimate_mode in
c)
    estimate_mode=CONSERVATIVE
    ;;
e)
    estimate_mode=ECONOMICAL
    ;;
esac

for x in $(seq 1 $n)
do
  bitcoin-cli estimatesmartfee $x "$estimate_mode"
done \
  | sed -e 's,\(0.[0-9]\+\),"\1",g' \
  | jq -r "[\"feerate\", \"blocks\", \"hours\", \"fiat\"],[.feerate, .blocks, (((.blocks * 10)/60)*100 | floor)/100, (.feerate | tonumber | ((. * $size)/1000) * $price) ] | @tsv" \
  | sort -n -u -t$'\t' -k1,1 \
  | column -t -s $'\t'


